# Generated by Django 5.2.17 on 2026-08-25 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('clipboard', '0002_clipboardstate_device'),
    ]

    operations = [
        migrations.CreateModel(
            name='PairingCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('is_used', models.BooleanField(default=False)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('desktop_device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pairing_codes', to='clipboard.device')),
            ],
            options={
                'ordering': ('-created_at',),
            },
        ),
    ]
