from __future__ import annotations

from datetime import timedelta
from django.contrib.auth.models import User
from django.db import models
from django.utils import timezone


class DeviceType(models.TextChoices):
    DESKTOP = "desktop", "Desktop"
    ANDROID = "android", "Android"


class Device(models.Model):
    """A registered hardware device belonging to a User."""

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name="devices")
    device_id = models.CharField(max_length=100, unique=True)
    device_type = models.CharField(
        max_length=20,
        choices=DeviceType.choices,
        default=DeviceType.DESKTOP,
    )
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ("-created_at",)

    def __str__(self) -> str:
        return f"{self.user.username} - {self.device_id} ({self.device_type})"


class ClipboardState(models.Model):
    """The single active text clipboard state for a User with 10-minute expiration."""

    user = models.OneToOneField(
        User,
        on_delete=models.CASCADE,
        related_name="clipboard_state",
    )
    content = models.TextField()
    updated_at = models.DateTimeField(auto_now=True)
    expires_at = models.DateTimeField()

    def is_expired(self) -> bool:
        return timezone.now() >= self.expires_at

    def __str__(self) -> str:
        return f"{self.user.username}: {self.content[:30]} (expires {self.expires_at})"


class PairingCode(models.Model):
    """A temporary, single-use code generated by a desktop device to pair an Android device."""

    desktop_device = models.ForeignKey(
        Device,
        on_delete=models.CASCADE,
        related_name="pairing_codes",
    )
    code = models.CharField(max_length=20, unique=True)
    created_at = models.DateTimeField(auto_now_add=True)
    expires_at = models.DateTimeField()
    is_used = models.BooleanField(default=False)
    used_at = models.DateTimeField(null=True, blank=True)

    class Meta:
        ordering = ("-created_at",)

    def is_valid(self) -> bool:
        return not self.is_used and timezone.now() < self.expires_at

    def __str__(self) -> str:
        status = "used" if self.is_used else ("expired" if timezone.now() >= self.expires_at else "valid")
        return f"{self.code} ({self.desktop_device.device_id} - {status})"


class ClipboardEntry(models.Model):
    """Legacy historical log of clipboard values received from development devices."""

    device_id = models.CharField(max_length=100)
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ("-created_at", "-id")

    def __str__(self) -> str:
        return f"{self.device_id}: {self.content[:50]}"
