from __future__ import annotations

from rest_framework import status
from rest_framework.request import Request
from rest_framework.response import Response
from rest_framework.views import APIView

from django.contrib.auth.models import User
from clipboard.models import ClipboardEntry, DeviceType
from clipboard.serializers import (
    ClipboardEntrySerializer,
    ClipboardStateSerializer,
    DevicePairSerializer,
    PairingCodeCreateSerializer,
)
from clipboard.services import (
    create_pairing_code,
    get_active_user_clipboard,
    pair_android_device,
    resolve_device_and_user,
    set_user_clipboard,
)


class ClipboardEntryCreateView(APIView):
    """Create a clipboard entry and update the user's active ClipboardState."""

    def post(self, request: Request) -> Response:
        serializer = ClipboardEntrySerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        device_id = serializer.validated_data["device_id"]
        content = serializer.validated_data["content"]

        device, user = resolve_device_and_user(device_id)
        if user:
            set_user_clipboard(user, content)

        entry = serializer.save()
        return Response(ClipboardEntrySerializer(entry).data, status=status.HTTP_201_CREATED)


class LatestClipboardEntryView(APIView):
    """Return the user-scoped active ClipboardState if not expired."""

    def get(self, request: Request) -> Response:
        device_id = request.query_params.get("device_id")
        user = None

        if device_id:
            _, user = resolve_device_and_user(device_id)
        else:
            user = User.objects.first()

        if user is None:
            return Response(
                {"detail": "No clipboard entries found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        state = get_active_user_clipboard(user)
        if state is None:
            return Response(
                {"detail": "No clipboard entries found."},
                status=status.HTTP_404_NOT_FOUND,
            )

        response_data = {
            "id": state.id,
            "device_id": device_id or (user.devices.first().device_id if user.devices.exists() else "unknown"),
            "content": state.content,
            "updated_at": state.updated_at,
            "expires_at": state.expires_at,
        }
        return Response(response_data, status=status.HTTP_200_OK)


class PairingCodeCreateView(APIView):
    """Generate a temporary pairing code for a desktop device."""

    def post(self, request: Request) -> Response:
        serializer = PairingCodeCreateSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        device_id = serializer.validated_data["device_id"]
        device, user = resolve_device_and_user(device_id, default_type=DeviceType.DESKTOP)

        if not device or device.device_type != DeviceType.DESKTOP:
            return Response(
                {"detail": "Pairing codes can only be generated by desktop devices."},
                status=status.HTTP_400_BAD_REQUEST,
            )

        pairing_code = create_pairing_code(device)
        return Response(
            {
                "code": pairing_code.code,
                "expires_at": pairing_code.expires_at,
            },
            status=status.HTTP_201_CREATED,
        )


class DevicePairView(APIView):
    """Pair an Android device with a desktop device using a pairing code."""

    def post(self, request: Request) -> Response:
        serializer = DevicePairSerializer(data=request.data)
        serializer.is_valid(raise_exception=True)

        code_str = serializer.validated_data["code"]
        android_device_id = serializer.validated_data["android_device_id"]

        android_device, error = pair_android_device(code_str, android_device_id)
        if error:
            if "already paired with another user" in error:
                return Response({"detail": error}, status=status.HTTP_409_CONFLICT)
            elif "expired" in error or "used" in error or "required" in error or "desktop device" in error:
                return Response({"detail": error}, status=status.HTTP_400_BAD_REQUEST)
            else:
                return Response({"detail": error}, status=status.HTTP_404_NOT_FOUND)

        return Response(
            {
                "status": "paired",
                "device_id": android_device.device_id,
                "user_id": android_device.user.id,
                "user_name": android_device.user.username,
            },
            status=status.HTTP_200_OK,
        )
